function [budengshi]=aaabudengshi_constraint(X) 
ddx=X(1);
dx=X(2);
x=X(3);
ddy=X(4);
dy=X(5);
y=X(6);
ux=X(7);
uy=X(8);

joint_range_constraint=[...
    -x-0.9;...
    x-0.9;...
    -ux-1;...
    ux-1;...
    -uy-1;...
    uy-1;...
    sqrt(ux^2+uy^2)-1];

%sqrt(ux^2+uy^2)-0.6
budengshi=[joint_range_constraint];
